In [60]:
# Задание №1
import numpy as np

a = np.matrix([[1, 2, 1], [-2, 1, 1]])
b = np.matrix([[3, 1], [-1, 0], [2, 4]])
c = np.matrix([[-2, 2], [1, -1], [1, 2]])
r1 = np.vstack([a, [0, 0 , 0]]) + np.append(2*b, [[0], [0], [0]], axis=1)
r2 = b + np.dot(2,c)
print('Результат вычисления A + 2B:\n' + str(r1))
print('Результат вычисления B + 2C:\n' + str(r2))

Результат вычисления A + 2B:
[[ 7  4  1]
 [-4  1  1]
 [ 4  8  0]]
Результат вычисления B + 2C:
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [31]:
# Задание №2
zero = np.zeros((8,8), dtype=int)
zero[1::2,::2] = 1
zero[::2,1::2] = 1
print('Вывод элементов в шахматном порядке: \n' + str(zero))

Вывод элементов в шахматном порядке: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# Задание №3
v1 = np.arange(0, 1.5, 0.1)
v2 = np.arange(1, 7)
v = np.dot(v1.reshape(5, 3), v2.reshape(3, 2))
print(v)

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [69]:
# Задание №4
a = [1]
while len(a) != 36:
  a.append(a[-1] + 2)
v = np.array(a)
res_v = v[v % 3 == 0]
print('Исходный вектор:\n' + str(v))
print('Вектор со значениями кратными 3:\n' + str(res_v))

Исходный вектор:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Вектор со значениями кратными 3:
[ 3  9 15 21 27 33 39 45 51 57 63 69]
